### ISSUE TITLE
How to recreate CJS behavior wrt to resolving directories?

### ISSUE THREAD

**Issue by mgol** [wycats/jsmodules#6]
Node's `require('m')` in module `n` searches for the main file of the module `m` in `node_modules` of `n`; path resolving is done automatically. That's when we have the structure:

```
├─┬ n
  ├─┬ node_modules
    ├── m
```

If module `m` doesn't exist within `n`'s `node_modules` but exists within it's siblings:

```
├── n
├── m
```

then `require('m')` resolves to the sibling.

When people will evaluate switching from `require` to ES6 modules in Node, they'll need to know how to recreate this logic in ES6 so that they don't have to resolve paths by themselves.

Can this be done? If so, maybe putting this on a site would be useful?

**Comment by calvinmetcalf** [comment]
Basically you need to use the normalize hook in the loader to resolve it cjs style, the [resolver from browserify](https://github.com/substack/node-resolve), I have a [project related to loading cjs with es6 modules](https://github.com/calvinmetcalf/es6-translate) if your interested in all the gory details.

**Comment by wycats** [comment]
The plan is for the browser-provided loader to offer this functionality. A Node loader would of course provide node-compatible behavior as well.

Transpilers are also including support for it.

The interesting thing is that even though the semantics seem equivalent between platforms at first glance, because of the differences between how modules are actually loaded, this normalization happens at the Loader level, which is platform specific.

We expect Loaders to respect the `.` and `..` conventions because they are so popular and common. We're also exploring ways to express the expected semantics in a network/file agnostic way.

**Comment by mgol** [comment]
Thanks for replies!
